### ISSUE TITLE
Invalid block tag on line 48: 'render_zone', expected 'endblock'. Did you forget to register or load this tag?

### ISSUE THREAD

**Issue by g33k44** [razisayyed/django-ads#1]
it gives me this error when i try to render a zone .  {% render_zone 'content' %}
please note that i've loaded the ads tags {% load ads_tags %}
i'm using Django 1.10

**Comment by razisayyed** [comment]
@g33k44 did you add 'ads' to your INSTALLED_APPS?

**Comment by g33k44** [comment]
yes

**Comment by razisayyed** [comment]
@g33k44 sorry, it is my mistake. I renamed the tag and forgot to update the docs. The tag name is render_ads_zone.

{% render_ads_zone "content" %}
